# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveIntegerField(default=60)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.URL')),
            ],
        ),
    ]
